builders:
  openapi_freezed_dio_builder:
    import: 'package:openapi_freezed_dio_builder/openapi_freezed_dio_builder.dart'
    builder_factories: ['openapiCodeBuilder']
    build_extensions: {".openapi.yaml": [".openapi.dart"]}
    auto_apply: dependents
#    build_to: cache
    build_to: source
    runs_before: ['json_serializable|json_serializable']
